[package]
name = "mw-client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Sync Unix-socket client SDK for MicroWAF"

[lints]
workspace = true

[dependencies]
mw-proto = { path = "../mw-proto" }
dcc-daemon = { git = "https://github.com/dcc-bigfred/rust-commons.git", rev = "bdc4155f124f82ce59c9a8801b4952be8e06f4a2", default-features = false }
thiserror = "2"
serde_json = "1"

[dev-dependencies]
tempfile = "3"
